// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using etherscan_test;

#nullable disable

namespace etherscan_test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Block", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(20)");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("int(20)");

                    b.Property<decimal>("BlockReward")
                        .HasColumnType("decimal(50,0)");

                    b.Property<decimal>("GasLimit")
                        .HasColumnType("decimal(50,0)");

                    b.Property<decimal>("GasUsed")
                        .HasColumnType("decimal(50,0)");

                    b.Property<string>("Hash")
                        .HasColumnType("varchar(66)");

                    b.Property<string>("Miner")
                        .HasColumnType("varchar(42)");

                    b.Property<string>("ParentHash")
                        .HasColumnType("varchar(66)");

                    b.HasKey("BlockId");

                    b.ToTable("Block", (string)null);
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(20)");

                    b.Property<int>("BlockId")
                        .HasColumnType("int(20)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("varchar(42)");

                    b.Property<decimal>("Gas")
                        .HasColumnType("decimal(50,0)");

                    b.Property<decimal>("GasPrice")
                        .HasColumnType("decimal(50,0)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varchar(66)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("varchar(42)");

                    b.Property<int>("TransactionIndex")
                        .HasColumnType("int(20)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(50,0)");

                    b.HasKey("TransactionId");

                    b.HasIndex("BlockId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.HasOne("Block", "Block")
                        .WithMany("Transactions")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("Block", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
